# Generated by Django 4.2.30 on 2026-05-26 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('SAP', 'SAP MM Procurement'), ('UTILITY', 'Utility Electricity Portal'), ('TRAVEL', 'Concur Flight Travel Log')], max_length=50)),
                ('scope_category', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct Emissions'), ('Scope 2', 'Scope 2 - Indirect Grid'), ('Scope 3', 'Scope 3 - Value Chain Travel')], max_length=50)),
                ('raw_payload', models.JSONField(help_text='Unmodified incoming raw payload block')),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('calculated_co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUSPICIOUS', 'Suspicious Data'), ('FAILED', 'Failed Ingestion'), ('APPROVED', 'Approved & Locked')], default='PENDING', max_length=50)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor')], default='ANALYST', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('field_modified', models.CharField(blank=True, max_length=100, null=True)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Justification for this update')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.activityrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.tenant'),
        ),
    ]
