# Generated by Django 4.2.30 on 2026-05-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_tenants',
            field=models.ManyToManyField(blank=True, related_name='assigned_analysts', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor')], default='ANALYST', max_length=50),
        ),
    ]
