# Generated by Django 4.2.30 on 2026-05-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_assigned_tenants_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='file_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
